# Generated by Django 2.1.7 on 2019-02-27 19:06

from django.db import migrations, models
import django_measurement.models
import measurement.measures.mass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fermentable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=250)),
                ('color', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('extract', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('moisture', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('mash_required', models.BooleanField()),
                ('quantity', django_measurement.models.MeasurementField(default=0, measurement=measurement.measures.mass.Mass)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
